// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20181204095524_createtable1")]
    partial class createtable1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanLyThuVien.Models.ChiNhanh", b =>
                {
                    b.Property<int>("IDChiNhanh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired();

                    b.Property<int>("IDNhanVien");

                    b.Property<int>("IDQuanLy");

                    b.Property<DateTime>("NgayThanhLap");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired();

                    b.HasKey("IDChiNhanh");

                    b.ToTable("ChiNhanhs");
                });

            modelBuilder.Entity("QuanLyThuVien.Models.Sach", b =>
                {
                    b.Property<int>("IDSach")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LoaiSach");

                    b.Property<string>("MoTa");

                    b.Property<int>("NamXuatBan");

                    b.Property<DateTime>("NgayNhap");

                    b.Property<string>("NhaXuatBan");

                    b.Property<int>("SoDanhGia");

                    b.Property<int>("SoSachCon");

                    b.Property<int>("SoTrang");

                    b.Property<string>("TacGia");

                    b.Property<string>("TenSach")
                        .IsRequired();

                    b.Property<int>("TongSoLuong");

                    b.Property<float>("XepHangTb");

                    b.HasKey("IDSach");

                    b.ToTable("Saches");
                });

            modelBuilder.Entity("QuanLyThuVien.Models.SachChiNhanh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDChiNhanh")
                        .HasMaxLength(6);

                    b.Property<int>("IDSach")
                        .HasMaxLength(6);

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IDSach");

                    b.ToTable("SachChiNhanhs");
                });

            modelBuilder.Entity("QuanLyThuVien.Models.SachChiNhanh", b =>
                {
                    b.HasOne("QuanLyThuVien.Models.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuanLyThuVien.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("IDSach")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
